version: '3'
services:
  db:
    image: 'postgres:12'
    container_name: "postgres_container"
    ports:
      - "5432:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
volumes:
  my_dbdata: